### ISSUE TITLE
Get provisioning working on Xenial

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/packer-ubuntu-1604#1]
See upstream(ish) PR: https://github.com/chef/bento/pull/545

There are probably few changes required to the boot sequence and kickstart config.

**Comment by geerlingguy** [comment]
Upstream issue to get Ansible's official PPA working on Xenial: https://github.com/ansible/ansible/issues/15524

For now, I think I can install Ansible differently, and we should be okay.

**Comment by geerlingguy** [comment]
Maybe:

```
# Install pip.
apt -y install python-setuptools
easy_install pip

# Install Ansible.
pip install ansible
```

Otherwise I think Xenial has pip via `python-pip` as well.

**Comment by geerlingguy** [comment]
I think I've run into: https://github.com/mitchellh/vagrant/issues/6871

**Comment by geerlingguy** [comment]
Adding `net.ifnames=0 biosdevname=0` to the boot command didn't seem to help; if inside the built machine, `ifconfig` doesn't list an `eth0` interface :/

Tried from http://unix.stackexchange.com/a/88619/16194, but might need to do some other hackish thing, like was suggested in the original issue in bento.

**Comment by geerlingguy** [comment]
Trying `ln -s /dev/null /etc/udev/rules.d/80-net-setup-link.rules` to turn off the naming scheme for now. Will add to `cleanup.sh` if it works.

**Comment by geerlingguy** [comment]
That didn't work. And neither did `echo 'GRUB_CMDLINE_LINUX="net.ifnames=0"' >>/etc/default/grub` (both tested after a reboot).

**Comment by geerlingguy** [comment]
So some other places to read:

  - [PR: Handle new 'predictable' network interface naming style](https://github.com/mitchellh/vagrant/pull/7241)
  - [Predictable Network Interface Names](https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/)
  - [Ubuntu bug for livecd](https://bugs.launchpad.net/ubuntu/+source/livecd-rootfs/+bug/1538547)
  - [Ubuntu 15.10 error when enabling network interfaces](https://github.com/mitchellh/vagrant/issues/6871)


Trying this now:

```
echo 'GRUB_CMDLINE_LINUX="debian-installer=en_US net.ifnames=0"' >> /etc/default/grub
sudo grub-mkconfig -o /boot/grub/grub.cfg
sudo shutdown now
```

**Comment by geerlingguy** [comment]
Using the above gives the same result as my testing earlier—no `eth[x]` interfaces are created (`ifconfig` just lists the `lo` interface).

**Comment by geerlingguy** [comment]
Er, actually there _is_ an `eth0` and `eth1`. Needed to use `sudo ifconfig -a`.

**Comment by geerlingguy** [comment]
So the networking fix looks to be a combination of:

  1. Add `GRUB_CMDLINE_LINUX="biosdevname=0 net.ifnames=0"` to `/etc/default/grub`
  2. Run `sudo grub-mkconfig -o /boot/grub/grub.cfg` and reboot
  3. Edit `/etc/network/interfaces` and add in (replacing the existing default adapter<sup>1</sup>):

      ```
      auto eth0
      iface eth1 inet dhcp
      auto eth1
      iface eth1 inet manual
      ```

  4. Restart
  5. `vagrant up` should complete successfully.

<sup>1</sup> The definition of a semi-complete `eth1` adapter should not be required, but is currently because Ubuntu 16.04 (unlike previous releases) balks when there's an error message output during it's run of `ifdown eth1`. There's a commit that fixes this in vagrant master, but it's not in a stable release yet: https://github.com/mitchellh/vagrant/commit/0505771481222b4893daa5454ff6c9c16f471fa4

Also, the overarching problem is that Vagrant currently doesn't handle predictable network interfaces, which are now used by most of the major distros; there's a PR (https://github.com/mitchellh/vagrant/pull/7241) which aims to add in support, but it could be some time before that gets in.

I'm testing adding in all the above to `cleanup.sh` for now.

**Comment by sl4m** [comment]
@geerlingguy Had followed your steps in https://github.com/geerlingguy/packer-ubuntu-1604/issues/1#issuecomment-213130111, but it has a mistake. The edit to `/etc/network/interfaces` should be:

```
auto eth0
iface eth0 inet dhcp
auto eth1
iface eth1 inet manual
```

I figured it out from https://github.com/geerlingguy/packer-ubuntu-1604/commit/6ff79480c88d60c925e4673b2b0fdef379fc245c. Thanks for posting this fix.

**Comment by blowski** [comment]
For future reference, having done the first two steps mentioned above:

> 1. Add GRUB_CMDLINE_LINUX="biosdevname=0 net.ifnames=0" to /etc/default/grub
> 2. Run sudo grub-mkconfig -o /boot/grub/grub.cfg and reboot

The first time I booted the VM, it hung for about 2 minutes on a message about "Journal Started"  (sorry I can't remember the exact message). Then it was all fine and it fixed the problem. Future boots were normal.

Thanks for the fix.

**Comment by dsbaars** [comment]
I fixed this by appending by using the networking.d folder:
```bash
echo "auto eth1" >> /etc/network/interfaces.d/eth1
echo "iface eth1 inet manual" >> /etc/network/interfaces.d/eth1

echo "auto eth2" >> /etc/network/interfaces.d/eth2
echo "iface eth2 inet manual" >> /etc/network/interfaces.d/eth2

echo "auto eth3" >> /etc/network/interfaces.d/eth3
echo "iface eth3 inet manual" >> /etc/network/interfaces.d/eth3
```

**Comment by iduodu** [comment]
@dsbaars your fix does not work for me
