### ISSUE TITLE
error

### ISSUE THREAD

**Issue by abdidarmawan007** [geerlingguy/packer-ubuntu-1604#12]
where is folder in ansible?

geerlingguy.nfs
 geerlingguy.packer-debian

**Comment by abdidarmawan007** [comment]
vmware-iso: Errors were encountered while processing:
    vmware-iso: sudo
    vmware-iso: E: Sub-process /usr/bin/dpkg returned an error code (1)
==> vmware-iso: Stopping virtual machine...
==> vmware-iso: Deleting output directory...
Build 'vmware-iso' errored: Script exited with non-zero exit status: 100

**Comment by geerlingguy** [comment]
Before use, you have to run the command `ansible-galaxy install -r requirements.txt` (see the README file).
