### ISSUE TITLE
VMware boxes built with Fusion 8.5 get stuck on 'Waiting for machine to boot' step

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/packer-ubuntu-1604#13]
```
$ vagrant up ubuntu1604 --provider=vmware_fusion
Bringing machine 'ubuntu1604' up with 'vmware_fusion' provider...
==> ubuntu1604: Cloning VMware VM: 'file://~/Downloads/vmware-ubuntu1604.box'. This can take some time...
==> ubuntu1604: Verifying vmnet devices are healthy...
==> ubuntu1604: Preparing network adapters...
==> ubuntu1604: Starting the VMware VM...
==> ubuntu1604: Waiting for machine to boot. This may take a few minutes...
```

Tested with Vagrant 1.8.6 and packer 0.10.2. Going to update Packer and see if that helps...

**Comment by geerlingguy** [comment]
Linking to https://github.com/mitchellh/packer/pull/4041 - hit with 0.11.0 bug https://github.com/mitchellh/packer/issues/4054

**Comment by geerlingguy** [comment]
Though I still get stuck on `Waiting for machine to boot. This may take a few minutes...` if I don't have `v.gui = true`... :/

**Comment by geerlingguy** [comment]
And using `vagrant up --debug`:

```
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

Though there is a debug message saying the machine is running:

```
DEBUG vmware: VM state requested. Current state: running
```

But earlier in the debug:

```
DEBUG subprocess: stdout: Error: The VMware Tools are not running in the virtual machine: /Users/jeff.geerling/Dropbox/VMs/ansible-role-test/.vagrant/machines/ubuntu1604/vmware_fusion/6822c461-5d89-40fc-96cd-171cc520cf2d/packer-ubuntu-16.04-amd64.vmx
```

And also:

```
DEBUG vmware_driver:   - ethernet0.pcislotnumber = 32
DEBUG vmware_driver:   - ethernet1.pcislotnumber = 33
DEBUG vmware_driver:   - ethernet0.generatedaddress = 00:0c:29:67:9d:b3
DEBUG vmware_driver:   - ethernet0.generatedaddressoffset = 0
DEBUG vmware_driver:   - ethernet1.generatedaddress = 00:0c:29:67:9d:bd
DEBUG vmware_driver:   - ethernet1.generatedaddressoffset = 10
DEBUG vmware_driver: Trying to get MAC address for ethernet0
DEBUG vmware_driver: No explicitly set MAC, looking or auto-generated one...
DEBUG vmware_driver:  -- MAC: 00:0c:29:67:9d:b3
 INFO vmware_driver: Reading DHCP lease for '00:0c:29:67:9d:b3' on 'vmnet8'
 INFO vmware_driver: DHCP leases file: [#<Pathname:/var/db/vmware/vmnet-dhcpd-vmnet8.leases>, #<Pathname:/var/db/vmware/vmnet-dhcpd-vmnet8.leases~>]
 INFO dhcp_lease_file: Initialized DHCP helper: /var/db/vmware/vmnet-dhcpd-vmnet8.leases
 INFO dhcp_lease_file: Looking for IP for MAC: 00:0c:29:67:9d:b3
 INFO dhcp_lease_file:   - IP: 
 INFO dhcp_lease_file: Initialized DHCP helper: /var/db/vmware/vmnet-dhcpd-vmnet8.leases~
 INFO dhcp_lease_file: Looking for IP for MAC: 00:0c:29:67:9d:b3
 INFO dhcp_lease_file:   - IP: 
```

**Comment by geerlingguy** [comment]
Related investigation: https://github.com/geerlingguy/ansible-role-packer-debian/issues/9

**Comment by geerlingguy** [comment]
Fun times... if it's hanging on the connection, and I simple start VMware Fusion (e.g. via Spotlight or in Finder/Dock), then Vagrant connects. Sounds like something wonky in Fusion itself, with 8.5 maybe?

**Comment by geerlingguy** [comment]
There was _just_ an 8.5.1 release today. Going to rebuild and see if it's working again. Then maybe try reinstalling Vagrant plugin for Fusion if that doesn't work...

**Comment by geerlingguy** [comment]
Opened https://github.com/mitchellh/vagrant/issues/7942 — I can't think of anything else at the moment... will have to keep on using my older box build :P

**Comment by bradallenfisher** [comment]
Im getting this with virtual box now as well. 
Virtual Box 5.026
Vagrant 1.8.6

I can file a separate issue, but I don't think this is exclusive to VMWare fusion. Let me know.

**Comment by geerlingguy** [comment]
@bradallenfisher - This is with boxes built through this configuration, not with the public `geerlingguy/ubuntu1404` base box on Atlas? (Just want to make sure I didn't push out a bad build!).

**Comment by bradallenfisher** [comment]
Good question. With a straight vagrant init using 1604 i can't get vagrant to boot. I think it may be happening with all xenial boxes atm?

**Comment by geerlingguy** [comment]
Yeah, Vagrant and Xenial have _not_ been best of friends lately. I don't want to pin it on systemd, since Debian, Fedora and CentOS boxes have been running great with systemd for months now... but there's always something in Xenial builds!

**Comment by eugene-manuilov** [comment]
I have the same issue with virtual box as well. If I understand it correctly, the issue happens because `systemd-networkd-wait-online.service` service keeps waiting while all network services start working. But for some reason something wrong happens and it keeps waiting till the end of timeout period which is 5 mins. Vagrant has lower timeout to connect to machine and can't connect to it. Is there any way to disable that service?

**Comment by zaiddabaeen** [comment]
Any updates on this? Did anybody get it to work for Ubuntu 16.04?

**Comment by geerlingguy** [comment]
Still can't get this working reliably :(

See some notes on https://github.com/geerlingguy/packer-ubuntu-1604/pull/17

Basically, I've given up on VMware for the foreseeable future; VirtualBox's performance and stability has made paying for VMware's 5-10% (marginal) performance gains totally not worth the 40-60% extra effort supporting it.

I will keep my really old box versions that still work published, but I'm not planning on adding support again until things are more stable or until Hashicorp's plugin/support gets more stable. I've already burned about $300 in licenses + 50 dev hours on this stuff, and I'm getting nowhere. VirtualBox works fine for my needs, not going to keep donating a ton of my time so that more people can used closed source software that's more fragile than the OSS alternative.

**Comment by JackTiber** [comment]
This is unfortunately still not resolved. Somewhat disappointed I didn't find this thread until today, but even with the latest versions of each piece, it is still hanging on "Waiting to Boot". 

My latest debug is here. https://github.com/mitchellh/vagrant/issues/8916

Unfortunate since I am deploying these boxes to a vSphere environment and it would be nice to use one provider for everything in the pipe.

**Comment by zaiddabaeen** [comment]
@JackTiber I do have it working, I believe I used this script: https://github.com/cbednarski/packer-ubuntu

**Comment by JackTiber** [comment]
Will give it a shot! From what I can tell, the templates look identical, with the notable exception that the ssh timeout is 20m haha. That is a long time to wait and see if it connects. The scripts include a couple of config changes that differ from my build though, so maybe those are the key.

Will report back later today. Fingers crossed!

**Comment by zaiddabaeen** [comment]
If that didn't work out for you, I maybe able to fish out my current configuration which I have been using since February on all the dev machines we have here.

**Comment by JackTiber** [comment]
Ok. I have zero idea on which exact package was causing the box from being able to connect to vagrant, but after changing ONLY the preseed.cfg to include full-upgrade for the iso image, it works. 

At some point I may take the time to actually find which package update fixed this issue, but it is working with my previous build template as expected. It also works with 16.04.03 instead of 16.04.02 as in the repo above. 

If anyone has an idea of exactly which package it is that might be the root of this, let me know as leaving full-upgrade on the dev boxes is something I would rather avoid for consistency across the network.

**Comment by geerlingguy** [comment]
See: https://github.com/geerlingguy/packer-ubuntu-1604/issues/42
