### ISSUE TITLE
Error on Boot - No valid rapl domain found in package 

### ISSUE THREAD

**Issue by FlxPeters** [geerlingguy/packer-ubuntu-1604#15]
Hi,

i have an issue with the box loaded from vagrant cloud. 

When the box is booting there is an error (see screenshot). The box is booting, but it takes much time. 

Enviroment: Ubuntu with Virtualbox 5 (also tested on Mac)

![flxpeterslemp-php7_default_1481487585770_71134 wird ausgefuhrt - oracle vm virtualbox_001](https://cloud.githubusercontent.com/assets/346241/21083136/173fcf2e-bfea-11e6-94b3-f01e5b7b6ab4.png)

**Comment by geerlingguy** [comment]
What version of VirtualBox are you running? I just rebuilt the boxes for VirtualBox 5.1.10 guest additions—but if you use an older version, you need to have `vagrant-vbguest` installed.

**Comment by FlxPeters** [comment]
A Update fixed the issue. Thx a lot!
