### ISSUE TITLE
[Question] ubuntu1604.json Why so many <bs> is used in the boot_command ?

### ISSUE THREAD

**Issue by it-praktyk** [geerlingguy/packer-ubuntu-1604#21]
In lines [28-31](https://github.com/geerlingguy/packer-ubuntu-1604/blob/master/ubuntu1604.json#L28-L31) of the file ubuntu1604.json I see a lot of a backpace codes <bs> .

I followed interactive installation of Ubuntu Server 16.04.2 and I don't see need of use them.

Can you explain why these codes were added?

Thank you!

**Comment by geerlingguy** [comment]
I think I recall viewing the installation interactively, and at least last time I did that, there was a lot of text that had to be deleted (thus the many backspaces) before the boot command could be typed in. I haven't monitored a full provision with the GUI in a few releases, though; maybe there isn't anything to delete anymore?

**Comment by it-praktyk** [comment]
Thx for answer.
