### ISSUE TITLE
Ubuntu 16.04.03 was released

### ISSUE THREAD

**Issue by it-praktyk** [geerlingguy/packer-ubuntu-1604#31]
[DistroWatch article](https://distrowatch.com/?newsid=09919).

I hope to find time to update to the newer version soon.

**Comment by it-praktyk** [comment]
Update is ready but I wait to accept my

**Comment by geerlingguy** [comment]
This has been fixed in https://github.com/geerlingguy/packer-ubuntu-1604/pull/30 — thanks!
