### ISSUE TITLE
Hangs on "Waiting for SSH to become available"

### ISSUE THREAD

**Issue by codingCoffee** [geerlingguy/packer-ubuntu-1604#37]
Always hangs on:
```
==> virtualbox-iso: Waiting 10s for boot...
==> virtualbox-iso: Typing the boot command...
==> virtualbox-iso: Waiting for SSH to become available...
```

I don't think it is a issue related to this repo, but would be grateful if anyone knows a solution to it.

**Comment by francis-io** [comment]
@codingCoffee did you solve this?

**Comment by codingCoffee** [comment]
@francis-io yup. It isn't an issue with this repo. The SSH takes a lot of time to connect. You just have to be patient and wait for it to connect. Also make sure you have the preceed.cfg in the http folder and the link to it in the `build.json` as done in this repo.
