### ISSUE TITLE
Does not work on Windows

### ISSUE THREAD

**Issue by JonasGroeger** [geerlingguy/packer-ubuntu-1604#4]
Thats what I get when running it on my Windows 10 machine:

```
PS C:\Users\jonas\Downloads\packer-ubuntu-1604> packer build .\ubuntu1604.json
virtualbox-iso output will be in this color.
vmware-iso output will be in this color.

2 error(s) occurred:

* role_paths: /etc/ansible/roles/geerlingguy.packer-debian is invalid: GetFileAttributesEx /etc/ansible/roles/geerlingguy.packer-debian: Das System kann den angegebenen Pfad nicht finden.
* role_paths: /etc/ansible/roles/geerlingguy.nfs is invalid: GetFileAttributesEx /etc/ansible/roles/geerlingguy.nfs: Das System kann den angegebenen Pfad nicht finden.
```

Seems like those paths are hardwired?

**Comment by geerlingguy** [comment]
Yeah, those paths are currently hardcoded... I don't know what's the best way to make them configurable—for now, you can modify those paths in `ubuntu1604.json` manually.

**Comment by rickyp72** [comment]
replace with:  

    "role_paths": [
        "c:\\Users\\<windows user>\\.babun\\cygwin\\etc\\ansible\\roles\\geerlingguy.packer-rhel"
      ]
